import Link from 'next/link';
import { Package, Wand2, Sparkles } from 'lucide-react';

export default function Universes() {
  return (
    <div style={{ maxWidth: 900 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 32 }}>
        <div className="page-header" style={{ marginBottom: 0 }}>
          <h1 className="page-title">My Universes</h1>
          <p className="page-subtitle">Your forged meme token brands and ecosystems.</p>
        </div>
        <Link href="/studio" className="btn btn-primary">
          <Wand2 size={14} /> Forge New
        </Link>
      </div>

      {/* Empty state */}
      <div className="glass-card no-hover" style={{ padding: 60, textAlign: 'center', borderStyle: 'dashed' }}>
        <div style={{
          width: 64, height: 64, borderRadius: 16,
          background: 'var(--bg-inset)', border: '1px solid var(--border-color)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          margin: '0 auto 20px',
        }}>
          <Package size={28} style={{ color: 'var(--text-muted)' }} />
        </div>
        <div style={{ fontWeight: 700, fontSize: 17, marginBottom: 8 }}>No Universes Yet</div>
        <p style={{ color: 'var(--text-secondary)', fontSize: 14, maxWidth: 380, margin: '0 auto 24px', lineHeight: 1.6 }}>
          Your AI-generated meme empires will appear here. Use the Forge Studio to create your first token brand.
        </p>
        <Link href="/studio" className="btn btn-primary" style={{ padding: '11px 24px' }}>
          <Sparkles size={14} /> Open Forge Studio
        </Link>
      </div>

      {/* What you'll see section */}
      <div style={{ marginTop: 32 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 16 }}>
          What gets saved
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 14 }}>
          {[
            { icon: '🎨', title: 'AI Logo', desc: 'Unique synthesized artwork for your token' },
            { icon: '📜', title: 'Token Lore', desc: 'Full narrative and description generated by GPT-4o' },
            { icon: '🚀', title: 'Launch Pack', desc: 'Ticker, tokenomics, and marketing strategy' },
          ].map(({ icon, title, desc }) => (
            <div key={title} className="glass-card no-hover" style={{ padding: 20 }}>
              <div style={{ fontSize: 28, marginBottom: 10 }}>{icon}</div>
              <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 6 }}>{title}</div>
              <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{desc}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
